export const products = [
  {
    id: 1,
    name: "Apex Performance Tee",
    category: "Men",
    subcategory: "Luxury T-Shirts",
    price: 189,
    originalPrice: 249,
    badge: "Best Seller",
    colors: ["#0C0A09", "#FAFAF9", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80",
    description: "Elite performance fabric engineered for maximum comfort and prestige.",
    rating: 4.9,
    reviews: 284,
    isNew: false,
    isLimited: false,
  },
  {
    id: 2,
    name: "Sovereign Oversized Tee",
    category: "Men",
    subcategory: "Oversized Premium Tees",
    price: 229,
    originalPrice: null,
    badge: "New Arrival",
    colors: ["#0C0A09", "#292524", "#A8A29E"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    description: "Oversized silhouette crafted from premium heavyweight cotton.",
    rating: 4.8,
    reviews: 156,
    isNew: true,
    isLimited: false,
  },
  {
    id: 3,
    name: "Obsidian Compression Set",
    category: "Men",
    subcategory: "Compression Wear",
    price: 349,
    originalPrice: null,
    badge: "Limited Edition",
    colors: ["#0C0A09", "#1C1917"],
    sizes: ["S", "M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    description: "Four-way stretch compression technology meets luxury construction.",
    rating: 5.0,
    reviews: 89,
    isNew: false,
    isLimited: true,
  },
  {
    id: 4,
    name: "Aurum Gold Hoodie",
    category: "Men",
    subcategory: "Luxury Hoodies",
    price: 449,
    originalPrice: null,
    badge: "Signature",
    colors: ["#0C0A09", "#CA8A04", "#FAFAF9"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1614495894810-c0bba89f3c36?w=600&q=80",
    description: "The pinnacle of luxury hoodies — heavyweight French terry with gold hardware.",
    rating: 4.9,
    reviews: 412,
    isNew: false,
    isLimited: false,
  },
  {
    id: 5,
    name: "Elite Seamless Leggings",
    category: "Women",
    subcategory: "Leggings",
    price: 289,
    originalPrice: 329,
    badge: "Best Seller",
    colors: ["#0C0A09", "#A8A29E", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1539794830467-1f1755804d13?w=600&q=80",
    description: "Second-skin compression with invisible seams and premium four-way stretch.",
    rating: 4.9,
    reviews: 521,
    isNew: false,
    isLimited: false,
  },
  {
    id: 6,
    name: "Prestige Sports Bra",
    category: "Women",
    subcategory: "Sports Bras",
    price: 179,
    originalPrice: null,
    badge: "New Arrival",
    colors: ["#0C0A09", "#FAFAF9", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80",
    description: "Medium-support luxury sports bra engineered for all-day comfort.",
    rating: 4.8,
    reviews: 198,
    isNew: true,
    isLimited: false,
  },
  {
    id: 7,
    name: "Dynasty Tracksuit",
    category: "Men",
    subcategory: "Tracksuits",
    price: 689,
    originalPrice: null,
    badge: "Limited Edition",
    colors: ["#0C0A09", "#CA8A04"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "https://images.unsplash.com/photo-1591291621164-2c6367723315?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1524863479829-916d8e77f114?w=600&q=80",
    description: "The ultimate luxury tracksuit. Crafted in Italy. Worn by champions.",
    rating: 5.0,
    reviews: 67,
    isNew: false,
    isLimited: true,
  },
  {
    id: 8,
    name: "Luxe Performance Set",
    category: "Women",
    subcategory: "Premium Sets",
    price: 489,
    originalPrice: null,
    badge: "Signature",
    colors: ["#0C0A09", "#A8A29E"],
    sizes: ["XS", "S", "M", "L"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    description: "Complete luxury activewear set. Matching bra and leggings in premium fabric.",
    rating: 4.9,
    reviews: 234,
    isNew: false,
    isLimited: false,
  },
];

export const collections = [
  {
    id: "best-sellers",
    label: "Best Sellers",
    description: "Our most coveted pieces",
  },
  {
    id: "new-arrivals",
    label: "New Arrivals",
    description: "Fresh from the atelier",
  },
  {
    id: "limited-edition",
    label: "Limited Edition",
    description: "Exclusive drops",
  },
  {
    id: "performance",
    label: "Performance",
    description: "Engineered for excellence",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Marcus Thompson",
    role: "Professional Athlete",
    text: "AURUM has completely redefined what I expect from sportswear. The quality is unmatched — every detail speaks to craftsmanship I've never experienced before.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: 2,
    name: "Sophia Chen",
    role: "Fitness Model & Entrepreneur",
    text: "I've worn every luxury activewear brand out there. AURUM is on a different level entirely. The fit, the fabric, the way it makes you feel — pure prestige.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: 3,
    name: "James Okafor",
    role: "CEO & Performance Coach",
    text: "When you perform at the highest level, every detail matters. AURUM understands this. Their compression wear is scientifically superior and aesthetically perfect.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
  },
  {
    id: 4,
    name: "Isabella Rossi",
    role: "Olympic Athlete",
    text: "The Obsidian Compression Set is a masterpiece. I trained in it, I wore it to events — it performs at the highest level while looking like luxury fashion.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
];

export const brandPillars = [
  {
    icon: "diamond",
    title: "Premium Materials",
    subtitle: "Elite Fabrics",
    description:
      "Every AURUM piece begins with the world's finest materials. We source exclusive performance fabrics, Egyptian cotton, and advanced technical textiles that perform at the peak of luxury.",
  },
  {
    icon: "precision",
    title: "Precision Construction",
    subtitle: "Engineered Perfection",
    description:
      "Our master craftspeople dedicate hundreds of hours to perfecting each silhouette. Flat-lock seams, reinforced stress points, and millimeter-precise cuts define the AURUM standard.",
  },
  {
    icon: "crown",
    title: "Timeless Luxury",
    subtitle: "Above Trends",
    description:
      "AURUM designs transcend seasons and trends. We create pieces built to last — in construction, in style, and in cultural relevance. Investment pieces. Heirlooms of performance.",
  },
];

export const stats = [
  { value: "12K+", label: "Elite Members" },
  { value: "98%", label: "Satisfaction Rate" },
  { value: "47", label: "Countries Served" },
  { value: "5★", label: "Average Rating" },
];
