export const products = [
  {
    id: 1,
    name: "Apex Performance Tee",
    category: "Men",
    subcategory: "Luxury T-Shirts",
    price: 189,
    originalPrice: 249,
    badge: "Best Seller",
    colors: ["#0C0A09", "#FAFAF9", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/product-1.svg",
    hoverImage: "/images/product-1b.svg",
    description: "Elite performance fabric engineered for maximum comfort and prestige.",
    rating: 4.9,
    reviews: 284,
    isNew: false,
    isLimited: false,
  },
  {
    id: 2,
    name: "Sovereign Oversized Tee",
    category: "Men",
    subcategory: "Oversized Premium Tees",
    price: 229,
    originalPrice: null,
    badge: "New Arrival",
    colors: ["#0C0A09", "#292524", "#A8A29E"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/images/product-2.svg",
    hoverImage: "/images/product-2b.svg",
    description: "Oversized silhouette crafted from premium heavyweight cotton.",
    rating: 4.8,
    reviews: 156,
    isNew: true,
    isLimited: false,
  },
  {
    id: 3,
    name: "Obsidian Compression Set",
    category: "Men",
    subcategory: "Compression Wear",
    price: 349,
    originalPrice: null,
    badge: "Limited Edition",
    colors: ["#0C0A09", "#1C1917"],
    sizes: ["S", "M", "L", "XL"],
    image: "/images/product-3.svg",
    hoverImage: "/images/product-3b.svg",
    description: "Four-way stretch compression technology meets luxury construction.",
    rating: 5.0,
    reviews: 89,
    isNew: false,
    isLimited: true,
  },
  {
    id: 4,
    name: "Aurum Gold Hoodie",
    category: "Men",
    subcategory: "Luxury Hoodies",
    price: 449,
    originalPrice: null,
    badge: "Signature",
    colors: ["#0C0A09", "#CA8A04", "#FAFAF9"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/product-4.svg",
    hoverImage: "/images/product-4b.svg",
    description: "The pinnacle of luxury hoodies — heavyweight French terry with gold hardware.",
    rating: 4.9,
    reviews: 412,
    isNew: false,
    isLimited: false,
  },
  {
    id: 5,
    name: "Elite Seamless Leggings",
    category: "Women",
    subcategory: "Leggings",
    price: 289,
    originalPrice: 329,
    badge: "Best Seller",
    colors: ["#0C0A09", "#A8A29E", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/product-5.svg",
    hoverImage: "/images/product-5b.svg",
    description: "Second-skin compression with invisible seams and premium four-way stretch.",
    rating: 4.9,
    reviews: 521,
    isNew: false,
    isLimited: false,
  },
  {
    id: 6,
    name: "Prestige Sports Bra",
    category: "Women",
    subcategory: "Sports Bras",
    price: 179,
    originalPrice: null,
    badge: "New Arrival",
    colors: ["#0C0A09", "#FAFAF9", "#CA8A04"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/product-6.svg",
    hoverImage: "/images/product-6b.svg",
    description: "Medium-support luxury sports bra engineered for all-day comfort.",
    rating: 4.8,
    reviews: 198,
    isNew: true,
    isLimited: false,
  },
  {
    id: 7,
    name: "Dynasty Tracksuit",
    category: "Men",
    subcategory: "Tracksuits",
    price: 689,
    originalPrice: null,
    badge: "Limited Edition",
    colors: ["#0C0A09", "#CA8A04"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: "/images/product-7.svg",
    hoverImage: "/images/product-7b.svg",
    description: "The ultimate luxury tracksuit. Crafted in Italy. Worn by champions.",
    rating: 5.0,
    reviews: 67,
    isNew: false,
    isLimited: true,
  },
  {
    id: 8,
    name: "Luxe Performance Set",
    category: "Women",
    subcategory: "Premium Sets",
    price: 489,
    originalPrice: null,
    badge: "Signature",
    colors: ["#0C0A09", "#A8A29E"],
    sizes: ["XS", "S", "M", "L"],
    image: "/images/product-8.svg",
    hoverImage: "/images/product-8b.svg",
    description: "Complete luxury activewear set. Matching bra and leggings in premium fabric.",
    rating: 4.9,
    reviews: 234,
    isNew: false,
    isLimited: false,
  },
];

export const collections = [
  {
    id: "best-sellers",
    label: "Best Sellers",
    description: "Our most coveted pieces",
  },
  {
    id: "new-arrivals",
    label: "New Arrivals",
    description: "Fresh from the atelier",
  },
  {
    id: "limited-edition",
    label: "Limited Edition",
    description: "Exclusive drops",
  },
  {
    id: "performance",
    label: "Performance",
    description: "Engineered for excellence",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Marcus Thompson",
    role: "Professional Athlete",
    text: "AURUM has completely redefined what I expect from sportswear. The quality is unmatched — every detail speaks to craftsmanship I've never experienced before.",
    rating: 5,
    avatar: "/images/avatar-1.svg",
  },
  {
    id: 2,
    name: "Sophia Chen",
    role: "Fitness Model & Entrepreneur",
    text: "I've worn every luxury activewear brand out there. AURUM is on a different level entirely. The fit, the fabric, the way it makes you feel — pure prestige.",
    rating: 5,
    avatar: "/images/avatar-2.svg",
  },
  {
    id: 3,
    name: "James Okafor",
    role: "CEO & Performance Coach",
    text: "When you perform at the highest level, every detail matters. AURUM understands this. Their compression wear is scientifically superior and aesthetically perfect.",
    rating: 5,
    avatar: "/images/avatar-3.svg",
  },
  {
    id: 4,
    name: "Isabella Rossi",
    role: "Olympic Athlete",
    text: "The Obsidian Compression Set is a masterpiece. I trained in it, I wore it to events — it performs at the highest level while looking like luxury fashion.",
    rating: 5,
    avatar: "/images/avatar-4.svg",
  },
];

export const brandPillars = [
  {
    icon: "diamond",
    title: "Premium Materials",
    subtitle: "Elite Fabrics",
    description:
      "Every AURUM piece begins with the world's finest materials. We source exclusive performance fabrics, Egyptian cotton, and advanced technical textiles that perform at the peak of luxury.",
  },
  {
    icon: "precision",
    title: "Precision Construction",
    subtitle: "Engineered Perfection",
    description:
      "Our master craftspeople dedicate hundreds of hours to perfecting each silhouette. Flat-lock seams, reinforced stress points, and millimeter-precise cuts define the AURUM standard.",
  },
  {
    icon: "crown",
    title: "Timeless Luxury",
    subtitle: "Above Trends",
    description:
      "AURUM designs transcend seasons and trends. We create pieces built to last — in construction, in style, and in cultural relevance. Investment pieces. Heirlooms of performance.",
  },
];

export const stats = [
  { value: "12K+", label: "Elite Members" },
  { value: "98%", label: "Satisfaction Rate" },
  { value: "47", label: "Countries Served" },
  { value: "5★", label: "Average Rating" },
];
