import { Product, Collection, Review, JournalPost, Coupon } from './types';

// Product images - mapped from generated assets
const IMAGES = {
  blackTee: {
    front: 'https://image.qwenlm.ai/generated-images/55be5e51-274a-4f23-859c-4a4bffc688e4/_result.png',
    detail: 'https://image.qwenlm.ai/generated-images/b46946c9-0d6a-44eb-9509-507cdd3cf088/_result.png',
  },
  navyJacket: {
    front: 'https://image.qwenlm.ai/generated-images/f3fc663b-92ea-4290-acae-0b99cabaef90/_result.png',
  },
  whitePolo: {
    front: 'https://image.qwenlm.ai/generated-images/ccc04096-7092-4db5-9858-e4de1fbcfc3c/_result.png',
  },
  charcoalJoggers: {
    front: 'https://image.qwenlm.ai/generated-images/dc3ece90-ff37-418a-815b-e92acf33258d/_result.png',
  },
  cobaltTee: {
    front: 'https://image.qwenlm.ai/generated-images/3827b2e1-8051-4056-843a-797b6816030d/_result.png',
  },
  stoneHoodie: {
    front: 'https://image.qwenlm.ai/generated-images/5e3bd815-9d92-48b7-b4c0-c509950fc871/_result.png',
  },
  hero: 'https://image.qwenlm.ai/generated-images/b60a3017-1024-49f0-93c7-d28592101d0c/_result.png',
  lifestyle: 'https://image.qwenlm.ai/generated-images/2ad141c4-414b-437f-a729-bedd40d09074/_result.png',
  brandStory: 'https://image.qwenlm.ai/generated-images/532d81d5-0bbb-4773-be73-d31abb3ec710/_result.png',
};

export { IMAGES };

const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

function generateVariants(basePrice: number, stock: number, colors: string[]) {
  return colors.flatMap((color) =>
    SIZES.map((size, i) => ({
      id: `var-${color}-${size}`.toLowerCase().replace(/\s/g, '-'),
      sku: `KYV-${color.substring(0, 3).toUpperCase()}-${size}`,
      size,
      color,
      price: basePrice,
      stock: stock + Math.floor(Math.random() * 10) - 5,
      isAvailable: Math.random() > 0.1,
    }))
  );
}

export const products: Product[] = [
  {
    id: 'prod-001',
    slug: 'obsidian-performance-tee',
    name: 'Obsidian Performance Tee',
    description: 'Crafted from premium combed cotton with moisture-wicking technology, the Obsidian Performance Tee is engineered for those who demand excellence in every movement. The heavyweight 220 GSM fabric drapes with intention—structured enough to hold its shape through training, refined enough for daily wear. Reinforced shoulder seams and a slightly dropped hem ensure the silhouette stays sharp wash after wash.',
    shortDescription: 'Premium heavyweight cotton performance tee with moisture-wicking technology.',
    category: 't-shirts',
    collection: 'core-performance',
    gender: 'unisex',
    fabric: '220 GSM Combed Cotton Blend with Moisture-Wicking Finish',
    careInstructions: ['Machine wash cold with like colors', 'Do not bleach', 'Tumble dry low', 'Iron on low heat if needed', 'Do not dry clean'],
    fit: 'Regular athletic fit with slightly dropped hem',
    seoTitle: 'Obsidian Performance Tee | Premium Cotton T-Shirt | Kyveron',
    seoDescription: 'Premium heavyweight cotton performance tee. 220 GSM combed cotton with moisture-wicking technology. Designed for training and daily wear.',
    images: [
      { id: 'img-001-1', url: IMAGES.blackTee.front, alt: 'Black heavyweight cotton performance t-shirt, front view', order: 1, type: 'front' },
      { id: 'img-001-2', url: IMAGES.blackTee.detail, alt: 'Close-up of premium cotton fabric texture and stitching detail', order: 2, type: 'detail' },
    ],
    variants: generateVariants(249900, 25, ['Black', 'Charcoal']),
    basePrice: 249900,
    compareAtPrice: 299900,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    stockTotal: 150,
    rating: 4.7,
    reviewCount: 124,
    tags: ['bestseller', 'performance', 'daily-wear'],
    colors: ['Black', 'Charcoal'],
    sizes: SIZES,
  },
  {
    id: 'prod-002',
    slug: 'midnight-track-jacket',
    name: 'Midnight Track Jacket',
    description: 'The Midnight Track Jacket merges technical precision with refined aesthetics. Constructed from a lightweight nylon-spandex blend with a subtle matte finish, it moves with you—whether you are heading to a session or navigating the city. Raglan sleeves allow unrestricted movement, while the stand collar and zippered pockets add functional sophistication.',
    shortDescription: 'Lightweight technical track jacket with raglan sleeves and stand collar.',
    category: 'jackets',
    collection: 'core-performance',
    gender: 'men',
    fabric: 'Technical Nylon-Spandex Blend, 140 GSM',
    careInstructions: ['Machine wash cold, gentle cycle', 'Do not bleach', 'Hang dry', 'Do not iron directly on print', 'Do not dry clean'],
    fit: 'Slim athletic fit',
    seoTitle: 'Midnight Track Jacket | Technical Sports Jacket | Kyveron',
    seoDescription: 'Lightweight technical track jacket with raglan sleeves, stand collar, and zippered pockets. Premium nylon-spandex blend.',
    images: [
      { id: 'img-002-1', url: IMAGES.navyJacket.front, alt: 'Navy blue lightweight zip-up track jacket, front view', order: 1, type: 'front' },
    ],
    variants: generateVariants(499900, 15, ['Navy', 'Black']),
    basePrice: 499900,
    isFeatured: true,
    isNew: true,
    isPublished: true,
    stockTotal: 80,
    rating: 4.8,
    reviewCount: 67,
    tags: ['new-arrival', 'performance', 'layering'],
    colors: ['Navy', 'Black'],
    sizes: SIZES,
  },
  {
    id: 'prod-003',
    slug: 'ivory-classic-polo',
    name: 'Ivory Classic Polo',
    description: 'The Ivory Classic Polo redefines the everyday essential. Cut from premium pique cotton with a subtle textured hand-feel, it balances structure with softness. The two-button placket and ribbed collar are finished with precision, while the relaxed-but-tailored silhouette transitions seamlessly from casual to considered.',
    shortDescription: 'Premium pique cotton polo with textured finish and tailored fit.',
    category: 'polos',
    collection: 'daily-luxury',
    gender: 'men',
    fabric: 'Premium Pique Cotton, 200 GSM',
    careInstructions: ['Machine wash cold', 'Do not bleach', 'Tumble dry low', 'Warm iron if needed', 'Do not dry clean'],
    fit: 'Tailored fit with slight ease through body',
    seoTitle: 'Ivory Classic Polo | Premium Cotton Polo Shirt | Kyveron',
    seoDescription: 'Premium pique cotton polo shirt with textured finish. Tailored fit, two-button placket, ribbed collar. Everyday luxury.',
    images: [
      { id: 'img-003-1', url: IMAGES.whitePolo.front, alt: 'White premium pique cotton polo shirt, front view', order: 1, type: 'front' },
    ],
    variants: generateVariants(299900, 20, ['White', 'Stone', 'Navy']),
    basePrice: 299900,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    stockTotal: 120,
    rating: 4.6,
    reviewCount: 89,
    tags: ['classic', 'daily-wear', 'versatile'],
    colors: ['White', 'Stone', 'Navy'],
    sizes: SIZES,
  },
  {
    id: 'prod-004',
    slug: 'graphite-tailored-jogger',
    name: 'Graphite Tailored Jogger',
    description: 'Engineered for movement, refined for the street. The Graphite Tailored Jogger is cut from premium French terry with a brushed interior that feels as considered as it looks. The tapered leg and elasticated waistband with internal drawcord deliver a clean silhouette, while side pockets and a back welt pocket add everyday utility.',
    shortDescription: 'Premium French terry jogger with tapered leg and brushed interior.',
    category: 'joggers',
    collection: 'daily-luxury',
    gender: 'unisex',
    fabric: 'Premium French Terry Cotton, 320 GSM, Brushed Interior',
    careInstructions: ['Machine wash cold', 'Do not bleach', 'Tumble dry low', 'Do not iron on elastic', 'Do not dry clean'],
    fit: 'Tapered athletic fit',
    seoTitle: 'Graphite Tailored Jogger | Premium Cotton Joggers | Kyveron',
    seoDescription: 'Premium French terry jogger pants with tapered leg, brushed interior, and elasticated waistband. Designed for comfort and style.',
    images: [
      { id: 'img-004-1', url: IMAGES.charcoalJoggers.front, alt: 'Charcoal grey tailored jogger pants, front view', order: 1, type: 'front' },
    ],
    variants: generateVariants(349900, 18, ['Charcoal', 'Black', 'Stone']),
    basePrice: 349900,
    compareAtPrice: 399900,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    stockTotal: 100,
    rating: 4.9,
    reviewCount: 156,
    tags: ['bestseller', 'comfort', 'daily-wear'],
    colors: ['Charcoal', 'Black', 'Stone'],
    sizes: SIZES,
  },
  {
    id: 'prod-005',
    slug: 'cobalt-training-tee',
    name: 'Cobalt Training Tee',
    description: 'Purpose-built for high-intensity training. The Cobalt Training Tee uses a technical polyester-elastane blend with mesh ventilation panels at the sides for targeted airflow. The reinforced collar and slightly longer back hem ensure it stays in place through every rep, set, and sprint.',
    shortDescription: 'Technical training tee with mesh ventilation and reinforced construction.',
    category: 't-shirts',
    collection: 'core-performance',
    gender: 'unisex',
    fabric: 'Technical Polyester-Elastane Blend with Mesh Panels, 150 GSM',
    careInstructions: ['Machine wash cold', 'Do not bleach or use fabric softener', 'Hang dry recommended', 'Do not iron', 'Do not dry clean'],
    fit: 'Athletic performance fit',
    seoTitle: 'Cobalt Training Tee | Performance Training Top | Kyveron',
    seoDescription: 'Technical training t-shirt with mesh ventilation panels. Polyester-elastane blend for high-intensity workouts.',
    images: [
      { id: 'img-005-1', url: IMAGES.cobaltTee.front, alt: 'Deep cobalt blue performance training t-shirt, front view', order: 1, type: 'front' },
    ],
    variants: generateVariants(199900, 30, ['Cobalt Blue', 'Black', 'White']),
    basePrice: 199900,
    isFeatured: false,
    isNew: true,
    isPublished: true,
    stockTotal: 200,
    rating: 4.5,
    reviewCount: 43,
    tags: ['new-arrival', 'training', 'performance'],
    colors: ['Cobalt Blue', 'Black', 'White'],
    sizes: SIZES,
  },
  {
    id: 'prod-006',
    slug: 'stone-heritage-hoodie',
    name: 'Stone Heritage Hoodie',
    description: 'The Stone Heritage Hoodie is an exercise in considered comfort. Cut from premium brushed fleece cotton at 380 GSM, it has the weight and warmth of a garment made to last. The double-layered hood, kangaroo pocket, and ribbed cuffs and hem are finished with care—every stitch placed with intention.',
    shortDescription: 'Premium heavyweight brushed fleece hoodie with double-layered hood.',
    category: 'hoodies',
    collection: 'daily-luxury',
    gender: 'unisex',
    fabric: 'Premium Brushed Fleece Cotton, 380 GSM',
    careInstructions: ['Machine wash cold, inside out', 'Do not bleach', 'Tumble dry low', 'Do not iron on print or embroidery', 'Do not dry clean'],
    fit: 'Relaxed oversized fit',
    seoTitle: 'Stone Heritage Hoodie | Premium Cotton Hoodie | Kyveron',
    seoDescription: 'Premium heavyweight brushed fleece hoodie. 380 GSM cotton, double-layered hood, kangaroo pocket. Relaxed fit.',
    images: [
      { id: 'img-006-1', url: IMAGES.stoneHoodie.front, alt: 'Stone beige heavyweight cotton hoodie, front view', order: 1, type: 'front' },
    ],
    variants: generateVariants(399900, 12, ['Stone', 'Black', 'Charcoal']),
    basePrice: 399900,
    isFeatured: false,
    isNew: true,
    isPublished: true,
    stockTotal: 60,
    rating: 4.8,
    reviewCount: 78,
    tags: ['premium', 'comfort', 'winter'],
    colors: ['Stone', 'Black', 'Charcoal'],
    sizes: SIZES,
  },
];

export const collections: Collection[] = [
  {
    id: 'col-001',
    slug: 'core-performance',
    name: 'Core Performance',
    description: 'Engineered for movement. Technical fabrics, precise construction, and a refined silhouette—designed for those who train with intention and dress with purpose.',
    bannerImage: IMAGES.lifestyle,
    productCount: 3,
  },
  {
    id: 'col-002',
    slug: 'daily-luxury',
    name: 'Daily Luxury',
    description: 'Premium materials, considered design, everyday versatility. The Daily Luxury collection brings refined comfort to every moment of your day.',
    bannerImage: IMAGES.brandStory,
    productCount: 3,
  },
];

export const reviews: Review[] = [
  { id: 'rev-001', productId: 'prod-001', userId: 'user-001', userName: 'Arjun M.', rating: 5, title: 'Best tee I own', body: 'The fabric quality is exceptional. Fits perfectly and holds shape after multiple washes. Worth every rupee.', isVerified: true, createdAt: '2024-11-15' },
  { id: 'rev-002', productId: 'prod-001', userId: 'user-002', userName: 'Priya S.', rating: 4, title: 'Great quality, runs slightly large', body: 'Love the material and construction. I would suggest sizing down if you prefer a closer fit. Otherwise excellent.', isVerified: true, createdAt: '2024-11-20' },
  { id: 'rev-003', productId: 'prod-004', userId: 'user-003', userName: 'Rahul K.', rating: 5, title: 'Perfect joggers', body: 'The brushed interior is incredibly comfortable. Tapered fit looks sharp. These have become my everyday pants.', isVerified: true, createdAt: '2024-12-01' },
  { id: 'rev-004', productId: 'prod-002', userId: 'user-004', userName: 'Neha D.', rating: 5, title: 'Stunning jacket', body: 'The matte finish and raglan sleeves give this jacket a premium feel. Lightweight but warm enough for Bangalore evenings.', isVerified: true, createdAt: '2024-12-10' },
  { id: 'rev-005', productId: 'prod-006', userId: 'user-005', userName: 'Vikram T.', rating: 5, title: 'Heavyweight perfection', body: '380 GSM fleece is no joke. This hoodie has real substance. The double-layered hood sits perfectly. Premium quality.', isVerified: true, createdAt: '2024-12-15' },
];

export const coupons: Coupon[] = [
  { id: 'coup-001', code: 'KYVERON10', type: 'percentage', value: 10, minCartValue: 200000, maxDiscount: 100000, startDate: '2024-01-01', endDate: '2025-12-31', usageLimit: 1000, usedCount: 234, isActive: true },
  { id: 'coup-002', code: 'FIRST500', type: 'fixed', value: 50000, minCartValue: 250000, startDate: '2024-01-01', endDate: '2025-12-31', usageLimit: 500, usedCount: 89, isActive: true },
  { id: 'coup-003', code: 'PERF20', type: 'percentage', value: 20, minCartValue: 500000, maxDiscount: 200000, startDate: '2024-12-01', endDate: '2025-01-31', usageLimit: 200, usedCount: 45, isActive: true },
];

export const journalPosts: JournalPost[] = [
  {
    id: 'post-001',
    slug: 'the-art-of-fabric-selection',
    title: 'The Art of Fabric Selection',
    excerpt: 'How we source and test every material before it becomes part of a Kyveron garment.',
    content: 'Every Kyveron garment begins with a question: what does this fabric need to do? Before we select a material, we define its purpose—how it should drape, how it should move, how it should age. We test for pilling resistance, colour fastness, shrinkage, and hand-feel. Only fabrics that meet our standards move forward...',
    coverImage: IMAGES.brandStory,
    author: 'Kyveron Design Team',
    publishedAt: '2024-12-01',
    tags: ['craftsmanship', 'materials', 'quality'],
  },
  {
    id: 'post-002',
    slug: 'designing-for-movement',
    title: 'Designing for Movement',
    excerpt: 'The engineering decisions behind garments that move with you, not against you.',
    content: 'Performance apparel should disappear during activity. When you are training, the last thing you should think about is what you are wearing. We achieve this through raglan sleeves for unrestricted shoulder movement, gusseted seams for stretch, and strategic fabric weight distribution...',
    coverImage: IMAGES.lifestyle,
    author: 'Kyveron Design Team',
    publishedAt: '2024-11-15',
    tags: ['design', 'performance', 'engineering'],
  },
];
